### ISSUE TITLE
Minor error in formula for approximate method

### ISSUE THREAD

**Issue by jasondk** [ChaoranHu/coga#2]
FYI - I noticed there is a small discrepancy in the approxcoga.cpp get_A() function compared to the Barnabani (2017) paper.

In:
`double get_A(double mu, double mu2, double mu3) {
  double result = pow(mu * mu3 - 3 * pow(mu2, 2), 2) - 2;
  result /= mu * pow(mu2, 3);
  return result;
}
`

According to the definition given in Barnabani (2017) - p. 335, just below equation 6 - it appears this should actually be

`double get_A(double mu, double mu2, double mu3) {
  double result = pow(mu * mu3 - 3 * pow(mu2, 2), 2);
  result /= mu * pow(mu2, 3);
  result -= 2;
  return result;
}
`

Note: this made only a small difference in my application.

**Comment by ChaoranHu** [comment]
Hi Jasondk,
Thank you for your suggestion so much!
I will correct during September!

Best,
C

**Comment by ChaoranHu** [comment]
I have fixed the bug! Thank you again!
