### ISSUE TITLE
Question: using coga C++ code directly in Bayesian inference (Stan)

### ISSUE THREAD

**Issue by stemangiola** [ChaoranHu/coga#5]
I would like to infer alpha, beta parameters of a convoluted gamma distribution (3+ components). Is there a C++ file I can have a look to see the function I can use independently in platforms such a Stan.

What is the best choice in terms of efficiency/accuracy if such calculation must be do a very large number of times?

Thanks!

**Comment by lrnv** [comment]
Inference for convolutions is quite a hard problem, with current ongoing research. For gamma convolution, there is currently in my knowledge only one algorithm given by Furman & Al (2018). 'On lognormal convolutions .. something'. I am currently working on a better alternative, contact me if you are interested ;)

**Comment by ChaoranHu** [comment]
Sorry for the very late reply, @stemangiola! I believe you should already get this solved.
Just in case you still need them, they are stored in src folder.

-- C.Hu
